name: xmshop
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.18.6 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
#  屏幕适配
  flutter_screenutil: ^5.6.1
#  轮播图
  flutter_swiper_view: ^1.1.8
#  网络请求
  dio: ^4.0.6
#  瀑布流布局
  flutter_staggered_grid_view: ^0.6.2
#  数据缓存
  shared_preferences: ^2.0.17

  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
#  自定义图标
  fonts:
    - family: jokerFont
      fonts:
        - asset: assets/fonts/iconfont.ttf
#  自定义图片文件
  assets:
    - assets/images/xiaomiBanner.png
    - assets/images/2.0x/xiaomiBanner.png
    - assets/images/3.0x/xiaomiBanner.png
    - assets/images/xiaomiBanner2.png
    - assets/images/2.0x/xiaomiBanner2.png
    - assets/images/3.0x/xiaomiBanner2.png
    - assets/images/hotSearch.png
    - assets/images/2.0x/hotSearch.png
    - assets/images/3.0x/hotSearch.png

